language: rust

matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true
    include:
        - os: osx

        - os: linux
          rust: stable
          before_install:
            - sudo apt-get update -qq
            - sudo apt-get install -y libdbus-1-dev
        - os: linux
          rust: nightly
          before_install:
            - sudo apt-get update -qq
            - sudo apt-get install -y libdbus-1-dev

script:
  - cargo build --verbose
  - cargo run --verbose || true

cache: cargo
