[package]
name = "notify-rust-cli"
version = "0.2.0"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]

[[bin]]
name = "notify"

[dependencies]
notify-rust = "~3.1"
clippy = {version = "*", optional = true}

[dependencies.clap]
version = "2.1"
features = [ "suggestions", "color" ]

[features]
default = []
dev = ["clippy"]
