[package]
name = "toastify"
version = "0.3.1"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]

[dependencies]
notify-rust = {git= "https://github.com/hoodie/notify-rust/"}
clippy = {version = "*", optional = true}

[dependencies.clap]
version = "2"
features = [ "suggestions", "color" ]

[features]
default = []
dev = ["clippy"]
