[package]
name = "toastify"
version = "0.3.4"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]

keywords = ["desktop", "notification", "notify", "dbus", "libnotify"]
license = "MIT/Apache-2.0"
readme = "README.md"

[dependencies]
notify-rust = "3.5"

[dependencies.clap]
version = "2"
features = [ "suggestions", "color" ]
