[package]
name = "toastify"
version = "0.3.0"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]

[dependencies]
notify-rust = "~3.1"
clippy = {version = "*", optional = true}

[dependencies.clap]
version = "2.1"
features = [ "suggestions", "color" ]

[features]
default = []
dev = ["clippy"]
